services:
  rltrader:
    build: .
    container_name: rltrader
    volumes:
      - ./dataset:/app/dataset
      - ./models:/app/models
      - ./plots:/app/plots
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m scripts.run_rl_pipeline
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  datasetgen:
    build: .
    container_name: datasetgen
    volumes:
      - ./dataset:/app/dataset
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m scripts.dataset_generator