services:
  rltrader:
    build: .
    container_name: rltrader
    volumes:
      - ./dataset:/app/dataset
    environment:
      - PYTHONUNBUFFERED=1
    command: python run_rl_pipeline.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  datasetgen:
    build: .
    container_name: datasetgen
    volumes:
      - ./dataset:/app/dataset
    environment:
      - PYTHONUNBUFFERED=1
    command: python dataset_generator.py